### PR TITLE
Fix phase association

### LINKED ISSUE #125: Phase association issue (regression)
Well, I was testing [feature/iss-118](https://github.com/swiss-seismological-service/scdetect/tree/feature/iss-118) when I noticed something weird. When I run `scdetect-cc` on multiple stations & multiple channels and setting the `minimumArrivals` to 8 (for example) in the `template.json`, the code returns all possible detections and ignores completely this value. Same when I run `scdetect-cc` on master. 

Then I tried to set the value in the module (`scconfig`) and I got this

``` bash
15:36:07 [error/DETECT] Invalid configuration: 'minimumArrivals': 8. Must be < 0 or >= 1
Try --help for help
```

I pulled today the most recent master from seiscomp github page, but I have no idea if this issue is related to that.

### PR DESCRIPTION
**Pull request by damb**
**Bugfixes**:

- Fix phase association. Actually, this is a regression introduced with a1d8ce843ac81a09b82cc4930fc60a7ca639a80f.
- Fix default `minimumArrivals` module configuration parameter validation.

Closes #125.

### CODE REVIEW

**Comment by damb** [comment]
@mmesim, I checked the results visually by means of `scolv`. Could you check on your side, as well (to make sure that things are working properly now). Thanks.

**Comment by damb** [comment]
Besides, it would be good to add `ex-03` to the test suite. Perhaps it would be sufficient to use 10-20min of the data. Just to avoid another regression.

**Comment by mmesim** [comment]
> @mmesim, I checked the results visually by means of scolv. Could you check on your side, as well (to make sure that >things are working properly now)? Thanks.

Checked and works fine. Thanks a lot. 

PS. I checked the ex-03 with the data I sent you and it is ok. Perhaps you can add that to the test suite. :swimmer:

**Comment by damb** [comment]
Due to #129 and #130 at the time being it doesn't seem sensible to add `ex-03` to the test suite. Instead I'll merge this one. The test suite should include the `ex-03` test case once both #129 and #130 are fixed.

**Pull request merged**
