### PR TITLE
Fix detector triggering issues

### LINKED ISSUE #129: `"triggerDuration"` not correctly applied when making use of the `"minimumArrivals"` configuration parameter
While following the third offline playback example of the tutorial and playing around with the configuration I noted some inconsistencies regarding the first detector configuration (`"detectorId": "detector-01"`). The configuration uses `"minimumArrivals": 5`, i.e. according to the documentation a detection should be declared as soon as the number of associated phases is >= 5. Although, this works perfectly fine the duration between individual detections in some cases is smaller than the configured `"triggerDuration"`. E.g. `"detector-01"` uses `"triggerDuration": 0.5`, however there are 4 detections with origin times

```
2019-11-05T04:23:29.006707Z
2019-11-05T04:23:29.040707Z
2019-11-05T04:23:47.611707Z
2019-11-05T04:23:47.648707Z
```

Instead, I'd expect to obtain two detections, only.

The issue is caused by the fact that in the current implementation the `"triggerDuration"` is evaluated based on the earliest pick of the detection candidate. This approach works perfectly fine if the phase associated with the earliest pick of the template detection is included in the detection candidate. However, when making use of the `"minimumArrivals"` configuration parameter this is not necessarily the case anymore and as a result the final origin times between subsequent detections may be smaller than the configured `"triggerDuration"`.

### PR DESCRIPTION
**Pull request by damb**
**Bugfixes**:
- Evaluate the `"triggerDuration"` based on the detection candidates' origin time. This is particularly relevant if users make use of the `"minimumArrivals"` configuration parameter.
- Fix detection issues when triggering is enabled.
- Cover triggering (tests are mostly based on third offline playback example of the tutorial). Results were carefully reviewed. Tests should cover changes made within #126, as well.

Closes #129, #130.

### CODE REVIEW

**Comment by damb** [comment]
@mmesim, could you please carefully review the changes. Thanks.

**Comment by mmesim** [comment]
@damp I tried to run ex-03 with `triggerDuration` on and off. I get 9 and 12 detections which then , using `scevent` merge into 6 origins. Is that what you get too?

FYI. `triggerDuration` on means  `triggerDuration`=0.5 
        `triggerDuration` off means  `triggerDuration`=-1

If you chose a different value for the first case then the results might not be the same. (I guess)

**Comment by damb** [comment]
Thanks a lot for having a look into this, @mmesim.

> FYI. `triggerDuration` on means `triggerDuration=0.5`
> `triggerDuration off means `triggerDuration=-1`

That's correct. This is the configuration from the tutorial's third offline playback example.

Simply counting the number of detections is not enough. Below the detailed results:

- **Triggering disabled**:
  - `detector-01` (detections origin times):
    
     ```
     2019-11-05T04:10:21.924705Z
     2019-11-05T04:10:21.786705Z
     2019-11-05T04:23:29.006707Z
     2019-11-05T04:23:29.040707Z
     2019-11-05T04:23:47.611707Z
     2019-11-05T04:23:47.648707Z
     2019-11-05T04:24:30.104706Z
     2019-11-05T04:36:51.460707Z
     ```

    Overall 8 detections.

  - `detector-02` (detections origin times):
    
     ```
     2019-11-05T04:10:21.904287Z
     2019-11-05T04:23:47.736289Z
     2019-11-05T04:36:51.440289Z
     2019-11-05T04:37:59.676287Z
     ```
    4 detections.

  - The complete results: [ep-disabled.xml.gz](https://github.com/swiss-seismological-service/scdetect/files/9445282/ep-disabled.xml.gz). Note that neither template arrivals nor amplitudes/magnitudes were included.

- **Triggering enabled** (`"triggerDuration": 0.5`):
  - `detector-01` (detections origin times):
    
     ```
     2019-11-05T04:10:21.924705Z
     2019-11-05T04:23:29.006707Z
     2019-11-05T04:23:47.611707Z
     2019-11-05T04:24:30.104706Z
     2019-11-05T04:36:51.460707Z
     ```

    5 detections.

  - `detector-02` (detections origin times):
    
     ```
     2019-11-05T04:10:21.904287Z
     2019-11-05T04:23:47.736289Z
     2019-11-05T04:36:51.440289Z
     2019-11-05T04:37:59.676287Z
     ```

    4 detections. I.e. triggering did not affect the result.


  - The complete results: [ep-enabled.xml.gz](https://github.com/swiss-seismological-service/scdetect/files/9445285/ep-enabled.xml.gz). Note that neither template arrivals nor amplitudes/magnitudes were included.


Besides, I also verified the detections visually (e.g. by means of `scolv`). It would be great if you could do the same.

**Comment by mmesim** [comment]
@damb Checked. Everything looks ok.

**Pull request merged**
